name: Build Image

on:
  workflow_dispatch:
    inputs:
      mod_version:
        type: string
        required: false

env:
  MOD_VERSION: ${{ inputs.mod_version }}
  GITHUB_REPO: "caitlynrw/jf-yt-dlp" #don't modify
  ENDPOINT: "caitlynrw/jf-yt-dlp" #don't modify
  BASEIMAGE: "master"
  MODNAME: "yt-dlp"
  MULTI_ARCH: "false" #set to false if not needed

jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set Vars
        run: |
          echo "GITHUB_REPO=${{ env.GITHUB_REPO }}" >> $GITHUB_STEP_SUMMARY
          echo "ENDPOINT=${{ env.ENDPOINT }}" >> $GITHUB_STEP_SUMMARY
          echo "BASEIMAGE=${{ env.BASEIMAGE }}" >> $GITHUB_STEP_SUMMARY
          echo "MODNAME=${{ env.MODNAME }}" >> $GITHUB_STEP_SUMMARY
          echo "MULTI_ARCH=${{ env.MULTI_ARCH }}" >> $GITHUB_STEP_SUMMARY
          echo "MOD_VERSION=${MOD_VERSION}" >> $GITHUB_STEP_SUMMARY

  build:
    uses: linuxserver/github-workflows/.github/workflows/docker-mod-builder.yml@v1
    needs: set-vars
    secrets:
      CR_USER: ${{ secrets.CR_USER }}
      CR_PAT: ${{ secrets.CR_PAT }}
    with:
      GITHUB_REPO: ${{ needs.set-vars.outputs.GITHUB_REPO }}
      ENDPOINT: ${{ needs.set-vars.outputs.ENDPOINT }}
      BASEIMAGE: ${{ needs.set-vars.outputs.BASEIMAGE }}
      MODNAME: ${{ needs.set-vars.outputs.MODNAME }}
      MOD_VERSION: ${{ needs.set-vars.outputs.MOD_VERSION }}
